---
layout: post
title:  Day 008
ref: day-008
lang: zh
date:   2016-04-20 00:00:00 +0800
---

![](/images/Day008.png)

异常 (Exceptions，Build-in Exception 更多内容可以在 [这里](https://docs.python.org/2/library/exceptions.html)找到) ，指程序运行中出现不可预期的情况。

什么时候会发生，例如

- 使用超过列表范围的索引值，会产生 `IndexError`
- 类型转换，会产生 `TypeError`
- 引用一个不存在的变量，会产生 `NameError`
- 对不同类型的数据进行运算，在没有做强制类型转换的情况下，会产生 `TypeError`

对于异常处理的方法，

- 不理会 (非常不好)
- 返回一个错误值，需要额外代码做检查
- 停止程序执行，抛出单独异常的情况，在 Python 中我们称之为抛出异常(Raising an Exception)，`raise Exception("Error Information")`

在 Python 中处理异常，

Python 提供了处理异常的处理器 (Handler)，`try … expect …`

异常处理器会对特定的异常类型进行处理，

```python
try:
  f = open('filename.txt')
except IOError e:           
  # e is the actual error object
  # Exception propagation
  # Raise the exception to caller (See explanation below)
  raise Exception("Cannot open file")
```

Python 中常见的异常，

- `SyntaxError`，Python 不能解析程序中的语法
- `NameError`，找不到该变量名
- `AttributeError`，属性引用失败
- `TypeError`，运算类型不对
- `ValueError`，对错误的类型进行数据转换
- `IOError`，系统故障(文件没有找到)

自定义一个异常处理，

```python
class NetworkError(RuntimeError):
  def __init__(self, arg):
    self.args = arg

try:
  raise NetworkError("Bad hostname")
except NetworkError, e:
  print e.args
```

捕获所有异常，

```python
try:
  # Your code here
except:
  # Catch *all* exceptions
```

关于 `Try` 的扩展，

- `else` 语句，当没有异常发生时，则会执行 `else` 中的代码
- `finally` 语句， 会在 `try`，`except`，`else` 后执行，该语句一定会被执行，哪怕是遇到错误或是执行了 `break`，`continue` 或者 `return` 语句

一个简单的列子，

```python
def divide(x, y):
  try:
    result = x / y
  except ZeroDivisionError e:
    print str(e)
  except TypeError e:
    print str(e)
  except ValueError, Argument:
    print Argument
  else:
    # If there is NO exception
    print result
  finally:
    # Always get executed
    print "Finally Clause"
```

断言 (Assertions)指的是程序进行到某个时间点，断定其必然是某种状态，具体来讲，也就是断定改时间点上，某变量一定是某值，或是具有必定的属性。

Python 使用 `assert Expression[, Arguments]` 来进行断言。当假设与程序实际运行结果不符，在使用 `try-except` 语句处理异常时会抛出 `AssertionError`。

```python
def avg(grades, weights):
  # Raise AssertionException when list is empty
  assert not len(grades) == 0, 'No grades data'
  # Python list comprehension
  new_grade = [convertLetterGrade(elt) for elt in grades]
  return dotProduct(new_grade, weights) / len(new_grade)
```

使用断言进行防御性编程 (Defensive programming），

- 断言可以很好的控制在未知条件下程序的响应，当产生不可预期的情况时，断言会阻断程序的运行
- 通常用于检测程序的输入，同时也可以在任何地方使用
- 能够更容易的定位出程序出错的地方

使用断言可以有效的检测输入与输出的前提和后置条件，以避免错误的数值。

使用 `assert`，

- 检测参数的类型/数值
- 检查数据结构中的不变量是否满足
- 检查返回值是否满足约束条件
- 检查程序
